var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

// indexRouter and usersRouter are not required
// var indexRouter = require('./routes/index');
// var usersRouter = require('./routes/users');

// Importing the code from the routes directory for the Code Examples.
const expressRoutingSimpleRouteRouter
	= require('./routes/express/routing/simple-route');

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

// not used as / is for sphinx-documentation
// app.use('/', indexRouter);
// this application generator route is not needed
// app.use('/users', usersRouter);

// middlewares for the code examples
app.use('/code-examples/express/routing/simple-route',
	expressRoutingSimpleRouteRouter);

// this serves the html files generated by sphinx
app.use(express.static(path.join(__dirname,
	'sphinx-documentation/_build/html')));

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;
